"""PCG outer solver — direct port of PCG.C:69-238 (OpenFOAM PCG).

PCG is PBiCG without the transpose path. For symmetric pos-def A,
DILU degenerates to DIC (diagonal-based incomplete Cholesky), so we reuse
the same calc_reciprocal_d / precondition kernels — no separate code.

Convergence test (lduMatrixSolver.C):
    converged = (r_final < tol) OR (relTol > small_ AND r_final < relTol * r_initial)

Singular test (PCG.C):
    if |wApA| / normFactor < VSMALL=1e-300: break with singular flag.

This is the C++-backed version. A pure-Python+numba reference lives in
pbicg.py — by setting wT/rT/pT identical to wA/rA/pA, PBiCG reduces to
PCG, but the OpenFOAM xref dumps were generated by PCG so we must port
PCG verbatim for byte-exact match.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np

from .ldu import LDU
from .normfactor import NORM_FACTOR_SMALL
from . import _kernels_cpp as cpp


V_SMALL = 1e-300


@dataclass
class SolverPerformance:
    initial_residual: float
    final_residual: float
    n_iterations: int
    converged: bool
    singular: bool
    x: np.ndarray


def _converged(r_final: float, r_initial: float,
               tolerance: float, rel_tol: float) -> bool:
    if r_final < tolerance:
        return True
    if rel_tol > NORM_FACTOR_SMALL and r_final < rel_tol * r_initial:
        return True
    return False


def solve(ldu: LDU, b: np.ndarray, x0: np.ndarray,
          tolerance: float = 1e-12, rel_tol: float = 0.0,
          min_iter: int = 0, max_iter: int = 1000,
          sumA_override: Optional[np.ndarray] = None,
          nf_override: Optional[float] = None) -> SolverPerformance:
    """Solve A x = b with PCG-DIC starting from x0. Symmetric A required."""
    psi = x0.astype(np.float64, copy=True)
    source = b.astype(np.float64, copy=False)

    diag, lower, upper = ldu.diag, ldu.lower, ldu.upper
    owner, neighbour = ldu.owner, ldu.neighbour

    rD = cpp.calc_reciprocal_d(diag, lower, upper, owner, neighbour)

    A_psi = cpp.amul(diag, lower, upper, owner, neighbour, psi)
    rA = source - A_psi
    if nf_override is not None:
        nF = float(nf_override)
    else:
        if sumA_override is None:
            sa = cpp.sum_a(diag, lower, upper, owner, neighbour)
        else:
            sa = sumA_override
        psi_mean = float(psi.sum() / psi.size)
        sa_psibar = sa * psi_mean
        nF = float((np.abs(A_psi - sa_psibar) + np.abs(source - sa_psibar)).sum()
                   + NORM_FACTOR_SMALL)

    initial_residual = cpp.sum_abs(rA) / nF
    final_residual = initial_residual

    pA = np.zeros_like(psi)
    wArA = 0.0  # placeholder; iter==0 special-case avoids wArAold

    n_iter = 0
    converged = False
    singular = False

    while True:
        if n_iter >= max_iter:
            break
        if n_iter >= min_iter and converged:
            break

        wArAold = wArA
        wA = cpp.precondition(diag, lower, upper, owner, neighbour, rD, rA)
        wArA = cpp.dot(wA, rA)

        if n_iter == 0:
            pA = wA.copy()
        else:
            beta = wArA / wArAold
            pA = wA + beta * pA

        wA = cpp.amul(diag, lower, upper, owner, neighbour, pA)
        wApA = cpp.dot(wA, pA)

        if abs(wApA) / nF < V_SMALL:
            singular = True
            break

        alpha = wArA / wApA

        psi += alpha * pA
        rA -= alpha * wA

        final_residual = cpp.sum_abs(rA) / nF
        n_iter += 1
        converged = _converged(final_residual, initial_residual,
                                tolerance, rel_tol)

    return SolverPerformance(
        initial_residual=initial_residual,
        final_residual=final_residual,
        n_iterations=n_iter,
        converged=converged,
        singular=singular,
        x=psi,
    )
